name: binding_env2
channels:
  - conda-forge
  - "openbiosim/label/dev"
dependencies:
  - python>=3.9,<3.12
  - numpy
  - pandas
  - scipy
  - pydantic
  - ambertools
  - pymbar>=4.0
  - biosimspace>=2023.4 # has to be installed via conda