name: binding_env
channels:
  - conda-forge
  - "openbiosim/label/dev"
dependencies:
  - python>=3.9,<3.12
  - numpy
  - pandas
  - scipy
  - pydantic
  - ambertools
  - pymbar>=4.0  # need to pin this version to avoid issues with pymbar
  - biosimspace>=2023.4 # has to be installed via conda