# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-conda-pkgs-${{ hashFiles('environment.yaml') }}
  
      - name: Set up Conda (with Mamba)
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          environment-file: environment.yaml
          activate-environment: binding_env

      # Now **in a single login shell**, install everything and run pytest
      - name: Install & run tests (inside binding_env)
        shell: bash -l {0}
        run: |
          #  Activate the conda environment
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate binding_env

           # Confirm we are using the conda env’s python & pytest
          echo "Which python? $(which python)"
          echo "Python version: $(python --version)"
          echo "Which pytest?  $(which pytest || echo 'pytest not found yet')"

          pip install --no-deps .
          pip install .[test]

          pytest --maxfail=1 --disable-warnings -q